from django.core.exceptions import ValidationError

def file_size(value):
    filesize=value.size
    filesize>519437799
    



